### ISSUE TITLE
CARS98 paper results

### ISSUE THREAD

**Issue by farbodtm** [mangye16/Unsupervised_Embedding_Learning#4]
Hi Mang,

Great paper and thanks for sharing the code,
I am trying to reproduce your results on Cars dataset but I have not been able to do so with your current code. 31% R@1 33% NMI has been the best results I've gotten so far. I am assuming the code as its current state is not version you used to get the paper results for CARS. Is there anything i am missing? would appreciate your response.

Cheers

**Comment by mangye16** [comment]
Hi,

Thanks for your interest. We have modified parts of the code, especially for the loss function. To be honest, I haven't tested it on Car196 dataset.  Sorry (>v< ) 

We will figure it out and get back to you soon.

Alternatively, I have an older version of this code used in my paper. That version would be fine to reproduce all the results. I can send it to you by email if you are urgent. You can leave an email here.

Sorry for the caused inconvenience.

**Comment by farbodtm** [comment]
No problem, it'd be great if you could send it to me via email (i just sent you an email)

**Comment by mangye16** [comment]
Hi,

I delete my previous response. I have just tried the code and I can get similar results, which is quite close to the old version. Did you prepare the same dataset correctly?

I can still send you my older version code. Hope it helps your research. Thanks.
