### ISSUE TITLE
'CIFAR10Instance' object has no attribute 'train_data'

### ISSUE THREAD

**Issue by sudalvxin** [mangye16/Unsupervised_Embedding_Learning#6]
你好，我运行代码的时候报错：
'CIFAR10Instance' object has no attribute 'train_data'。
代码只是自己下载了数据集然后设置成了download=False

**Comment by mangye16** [comment]
The main reason is the version of torchvision is inconsistent. I suppose that you can try to replace:

```
        if self.train:
            img, target = self.train_data[index], self.train_labels[index]
        else:
            img, target = self.test_data[index], self.test_labels[index]
```
to        
```
        if self.train:
            img, target = self.data[index], self.targets[index]
        else:
            img, target = self.data[index], self.targets[index]
```

Meanwhile, you may need to change the evaluation code in 'utils.py'  Line 23:

`trainLabels = torch.LongTensor(trainloader.dataset.train_labels).cuda()`

to 

`trainLabels = torch.LongTensor(trainloader.dataset.targets).cuda()`

Hope it works for you!
