### ISSUE TITLE
about the loss

### ISSUE THREAD

**Issue by YanYan0716** [mangye16/Unsupervised_Embedding_Learning#8]
hello, thanks to show your code for us, and i am very sorry to distrub you that i can not understand the loss in the code, and i think it is different to the paper Eq.(6),  could you tell me if i was wrong or why they are different
of course, as a student, i am looking for your answer~~~
thanks again~~

**Comment by mangye16** [comment]
Hi, 

Thanks for the interest. The implementation is exactly the same with Eq. (6) when negM =1. We firstly compute Eq. (3) and (4) for all the samples within each sampled batch. You may debug it step by step. Or you may point out the line which you do not understand.
